# Generated by Django 4.2.4 on 2023-08-23 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='start'),
        ),
    ]
