# Generated by Django 4.2.4 on 2023-08-13 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='work center name')),
                ('description', models.TextField(verbose_name='work center description')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='is_deleted')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department', verbose_name='department')),
            ],
        ),
    ]
