# Generated by Django 4.2.4 on 2023-08-13 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('failure', '0001_initial'),
        ('workcenter', '0001_initial'),
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='failure',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reporter', to=settings.AUTH_USER_MODEL, verbose_name='reported by'),
        ),
        migrations.AddField(
            model_name='failure',
            name='solved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solver', to=settings.AUTH_USER_MODEL, verbose_name='solved by'),
        ),
        migrations.AddField(
            model_name='failure',
            name='work_center',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workcenter.workcenter', verbose_name='work center'),
        ),
        migrations.AddField(
            model_name='failure',
            name='work_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workorder.workorder', verbose_name='work order'),
        ),
    ]
