# Generated by Django 4.2.4 on 2023-08-19 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('failure', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failure',
            name='solved_by',
        ),
    ]
