from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import DepartmentViewSet

# Create a router and register the DepartmentViewSet with it
router = DefaultRouter()
router.register(r'departments', DepartmentViewSet, basename='department')

urlpatterns = [
    # Include the URLs generated by the router
    path('', include(router.urls)),
]
