# Generated by Django 4.2.4 on 2023-08-23 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('department', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='The timestamp when the department was created.', verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(help_text='A detailed description of the department.', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Indicates if the department is marked as deleted.', verbose_name='is deleted'),
        ),
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(help_text='The manager of the department (Foreign Key to User model).', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='manager'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='The name of the department.', max_length=150, verbose_name='department name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(help_text='The timestamp when the department was last updated.', null=True, verbose_name='Updated at'),
        ),
    ]
